/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ProtectedAuditRouteImport } from './routes/_protected/audit'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin'
import { Route as ProtectedElectionsIndexRouteImport } from './routes/_protected/elections/index'
import { Route as ProtectedElectionsIdRouteImport } from './routes/_protected/elections/$id'
import { Route as ProtectedElectionsIdResultsRouteImport } from './routes/_protected/elections/$id/results'
import { Route as ProtectedElectionsIdContestsRouteImport } from './routes/_protected/elections/$id/contests'
import { Route as ProtectedElectionsIdBallotsRouteImport } from './routes/_protected/elections/$id/ballots'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAuditRoute = ProtectedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedElectionsIndexRoute = ProtectedElectionsIndexRouteImport.update({
  id: '/elections/',
  path: '/elections/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedElectionsIdRoute = ProtectedElectionsIdRouteImport.update({
  id: '/elections/$id',
  path: '/elections/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedElectionsIdResultsRoute =
  ProtectedElectionsIdResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => ProtectedElectionsIdRoute,
  } as any)
const ProtectedElectionsIdContestsRoute =
  ProtectedElectionsIdContestsRouteImport.update({
    id: '/contests',
    path: '/contests',
    getParentRoute: () => ProtectedElectionsIdRoute,
  } as any)
const ProtectedElectionsIdBallotsRoute =
  ProtectedElectionsIdBallotsRouteImport.update({
    id: '/ballots',
    path: '/ballots',
    getParentRoute: () => ProtectedElectionsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof ProtectedAdminRoute
  '/audit': typeof ProtectedAuditRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/elections/$id': typeof ProtectedElectionsIdRouteWithChildren
  '/elections/': typeof ProtectedElectionsIndexRoute
  '/elections/$id/ballots': typeof ProtectedElectionsIdBallotsRoute
  '/elections/$id/contests': typeof ProtectedElectionsIdContestsRoute
  '/elections/$id/results': typeof ProtectedElectionsIdResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof ProtectedAdminRoute
  '/audit': typeof ProtectedAuditRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/elections/$id': typeof ProtectedElectionsIdRouteWithChildren
  '/elections': typeof ProtectedElectionsIndexRoute
  '/elections/$id/ballots': typeof ProtectedElectionsIdBallotsRoute
  '/elections/$id/contests': typeof ProtectedElectionsIdContestsRoute
  '/elections/$id/results': typeof ProtectedElectionsIdResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/admin': typeof ProtectedAdminRoute
  '/_protected/audit': typeof ProtectedAuditRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_protected/elections/$id': typeof ProtectedElectionsIdRouteWithChildren
  '/_protected/elections/': typeof ProtectedElectionsIndexRoute
  '/_protected/elections/$id/ballots': typeof ProtectedElectionsIdBallotsRoute
  '/_protected/elections/$id/contests': typeof ProtectedElectionsIdContestsRoute
  '/_protected/elections/$id/results': typeof ProtectedElectionsIdResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/audit'
    | '/auth/callback'
    | '/elections/$id'
    | '/elections/'
    | '/elections/$id/ballots'
    | '/elections/$id/contests'
    | '/elections/$id/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/audit'
    | '/auth/callback'
    | '/elections/$id'
    | '/elections'
    | '/elections/$id/ballots'
    | '/elections/$id/contests'
    | '/elections/$id/results'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/_protected/admin'
    | '/_protected/audit'
    | '/auth/callback'
    | '/_protected/elections/$id'
    | '/_protected/elections/'
    | '/_protected/elections/$id/ballots'
    | '/_protected/elections/$id/contests'
    | '/_protected/elections/$id/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/audit': {
      id: '/_protected/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof ProtectedAuditRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/elections/': {
      id: '/_protected/elections/'
      path: '/elections'
      fullPath: '/elections/'
      preLoaderRoute: typeof ProtectedElectionsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/elections/$id': {
      id: '/_protected/elections/$id'
      path: '/elections/$id'
      fullPath: '/elections/$id'
      preLoaderRoute: typeof ProtectedElectionsIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/elections/$id/results': {
      id: '/_protected/elections/$id/results'
      path: '/results'
      fullPath: '/elections/$id/results'
      preLoaderRoute: typeof ProtectedElectionsIdResultsRouteImport
      parentRoute: typeof ProtectedElectionsIdRoute
    }
    '/_protected/elections/$id/contests': {
      id: '/_protected/elections/$id/contests'
      path: '/contests'
      fullPath: '/elections/$id/contests'
      preLoaderRoute: typeof ProtectedElectionsIdContestsRouteImport
      parentRoute: typeof ProtectedElectionsIdRoute
    }
    '/_protected/elections/$id/ballots': {
      id: '/_protected/elections/$id/ballots'
      path: '/ballots'
      fullPath: '/elections/$id/ballots'
      preLoaderRoute: typeof ProtectedElectionsIdBallotsRouteImport
      parentRoute: typeof ProtectedElectionsIdRoute
    }
  }
}

interface ProtectedElectionsIdRouteChildren {
  ProtectedElectionsIdBallotsRoute: typeof ProtectedElectionsIdBallotsRoute
  ProtectedElectionsIdContestsRoute: typeof ProtectedElectionsIdContestsRoute
  ProtectedElectionsIdResultsRoute: typeof ProtectedElectionsIdResultsRoute
}

const ProtectedElectionsIdRouteChildren: ProtectedElectionsIdRouteChildren = {
  ProtectedElectionsIdBallotsRoute: ProtectedElectionsIdBallotsRoute,
  ProtectedElectionsIdContestsRoute: ProtectedElectionsIdContestsRoute,
  ProtectedElectionsIdResultsRoute: ProtectedElectionsIdResultsRoute,
}

const ProtectedElectionsIdRouteWithChildren =
  ProtectedElectionsIdRoute._addFileChildren(ProtectedElectionsIdRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRoute
  ProtectedAuditRoute: typeof ProtectedAuditRoute
  ProtectedElectionsIdRoute: typeof ProtectedElectionsIdRouteWithChildren
  ProtectedElectionsIndexRoute: typeof ProtectedElectionsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRoute,
  ProtectedAuditRoute: ProtectedAuditRoute,
  ProtectedElectionsIdRoute: ProtectedElectionsIdRouteWithChildren,
  ProtectedElectionsIndexRoute: ProtectedElectionsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
