/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VotersRegisterRouteImport } from './routes/voters/register'
import { Route as AuthSilentRenewRouteImport } from './routes/auth/silent-renew'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ProtectedAuditRouteImport } from './routes/_protected/audit'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin'
import { Route as ProtectedVotersIndexRouteImport } from './routes/_protected/voters/index'
import { Route as ProtectedElectionsIndexRouteImport } from './routes/_protected/elections/index'
import { Route as ProtectedVotersEligibilityRouteImport } from './routes/_protected/voters/eligibility'
import { Route as ProtectedVoteSessionRouteImport } from './routes/_protected/vote/session'
import { Route as ProtectedElectionsNewRouteImport } from './routes/_protected/elections/new'
import { Route as ProtectedElectionsIdRouteImport } from './routes/_protected/elections/$id'
import { Route as ProtectedElectionsIdResultsRouteImport } from './routes/_protected/elections/$id/results'
import { Route as ProtectedElectionsIdContestsRouteImport } from './routes/_protected/elections/$id/contests'
import { Route as ProtectedElectionsIdBallotsRouteImport } from './routes/_protected/elections/$id/ballots'
import { Route as ProtectedElectionsIdResultsTabulationRouteImport } from './routes/_protected/elections/$id/results/tabulation'
import { Route as ProtectedElectionsIdBallotsBallotIdPreviewRouteImport } from './routes/_protected/elections/$id/ballots/$ballotId/preview'
import { Route as ProtectedElectionsIdContestsContestIdCandidatesIndexRouteImport } from './routes/_protected/elections/$id/contests/$contestId/candidates/index'
import { Route as ProtectedElectionsIdContestsContestIdCandidatesReviewRouteImport } from './routes/_protected/elections/$id/contests/$contestId/candidates/review'
import { Route as ProtectedElectionsIdContestsContestIdCandidatesNewRouteImport } from './routes/_protected/elections/$id/contests/$contestId/candidates/new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VotersRegisterRoute = VotersRegisterRouteImport.update({
  id: '/voters/register',
  path: '/voters/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSilentRenewRoute = AuthSilentRenewRouteImport.update({
  id: '/auth/silent-renew',
  path: '/auth/silent-renew',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAuditRoute = ProtectedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedVotersIndexRoute = ProtectedVotersIndexRouteImport.update({
  id: '/voters/',
  path: '/voters/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedElectionsIndexRoute = ProtectedElectionsIndexRouteImport.update({
  id: '/elections/',
  path: '/elections/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedVotersEligibilityRoute =
  ProtectedVotersEligibilityRouteImport.update({
    id: '/voters/eligibility',
    path: '/voters/eligibility',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedVoteSessionRoute = ProtectedVoteSessionRouteImport.update({
  id: '/vote/session',
  path: '/vote/session',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedElectionsNewRoute = ProtectedElectionsNewRouteImport.update({
  id: '/elections/new',
  path: '/elections/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedElectionsIdRoute = ProtectedElectionsIdRouteImport.update({
  id: '/elections/$id',
  path: '/elections/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedElectionsIdResultsRoute =
  ProtectedElectionsIdResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => ProtectedElectionsIdRoute,
  } as any)
const ProtectedElectionsIdContestsRoute =
  ProtectedElectionsIdContestsRouteImport.update({
    id: '/contests',
    path: '/contests',
    getParentRoute: () => ProtectedElectionsIdRoute,
  } as any)
const ProtectedElectionsIdBallotsRoute =
  ProtectedElectionsIdBallotsRouteImport.update({
    id: '/ballots',
    path: '/ballots',
    getParentRoute: () => ProtectedElectionsIdRoute,
  } as any)
const ProtectedElectionsIdResultsTabulationRoute =
  ProtectedElectionsIdResultsTabulationRouteImport.update({
    id: '/tabulation',
    path: '/tabulation',
    getParentRoute: () => ProtectedElectionsIdResultsRoute,
  } as any)
const ProtectedElectionsIdBallotsBallotIdPreviewRoute =
  ProtectedElectionsIdBallotsBallotIdPreviewRouteImport.update({
    id: '/$ballotId/preview',
    path: '/$ballotId/preview',
    getParentRoute: () => ProtectedElectionsIdBallotsRoute,
  } as any)
const ProtectedElectionsIdContestsContestIdCandidatesIndexRoute =
  ProtectedElectionsIdContestsContestIdCandidatesIndexRouteImport.update({
    id: '/$contestId/candidates/',
    path: '/$contestId/candidates/',
    getParentRoute: () => ProtectedElectionsIdContestsRoute,
  } as any)
const ProtectedElectionsIdContestsContestIdCandidatesReviewRoute =
  ProtectedElectionsIdContestsContestIdCandidatesReviewRouteImport.update({
    id: '/$contestId/candidates/review',
    path: '/$contestId/candidates/review',
    getParentRoute: () => ProtectedElectionsIdContestsRoute,
  } as any)
const ProtectedElectionsIdContestsContestIdCandidatesNewRoute =
  ProtectedElectionsIdContestsContestIdCandidatesNewRouteImport.update({
    id: '/$contestId/candidates/new',
    path: '/$contestId/candidates/new',
    getParentRoute: () => ProtectedElectionsIdContestsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof ProtectedAdminRoute
  '/audit': typeof ProtectedAuditRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/silent-renew': typeof AuthSilentRenewRoute
  '/voters/register': typeof VotersRegisterRoute
  '/elections/$id': typeof ProtectedElectionsIdRouteWithChildren
  '/elections/new': typeof ProtectedElectionsNewRoute
  '/vote/session': typeof ProtectedVoteSessionRoute
  '/voters/eligibility': typeof ProtectedVotersEligibilityRoute
  '/elections/': typeof ProtectedElectionsIndexRoute
  '/voters/': typeof ProtectedVotersIndexRoute
  '/elections/$id/ballots': typeof ProtectedElectionsIdBallotsRouteWithChildren
  '/elections/$id/contests': typeof ProtectedElectionsIdContestsRouteWithChildren
  '/elections/$id/results': typeof ProtectedElectionsIdResultsRouteWithChildren
  '/elections/$id/results/tabulation': typeof ProtectedElectionsIdResultsTabulationRoute
  '/elections/$id/ballots/$ballotId/preview': typeof ProtectedElectionsIdBallotsBallotIdPreviewRoute
  '/elections/$id/contests/$contestId/candidates/new': typeof ProtectedElectionsIdContestsContestIdCandidatesNewRoute
  '/elections/$id/contests/$contestId/candidates/review': typeof ProtectedElectionsIdContestsContestIdCandidatesReviewRoute
  '/elections/$id/contests/$contestId/candidates/': typeof ProtectedElectionsIdContestsContestIdCandidatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof ProtectedAdminRoute
  '/audit': typeof ProtectedAuditRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/silent-renew': typeof AuthSilentRenewRoute
  '/voters/register': typeof VotersRegisterRoute
  '/elections/$id': typeof ProtectedElectionsIdRouteWithChildren
  '/elections/new': typeof ProtectedElectionsNewRoute
  '/vote/session': typeof ProtectedVoteSessionRoute
  '/voters/eligibility': typeof ProtectedVotersEligibilityRoute
  '/elections': typeof ProtectedElectionsIndexRoute
  '/voters': typeof ProtectedVotersIndexRoute
  '/elections/$id/ballots': typeof ProtectedElectionsIdBallotsRouteWithChildren
  '/elections/$id/contests': typeof ProtectedElectionsIdContestsRouteWithChildren
  '/elections/$id/results': typeof ProtectedElectionsIdResultsRouteWithChildren
  '/elections/$id/results/tabulation': typeof ProtectedElectionsIdResultsTabulationRoute
  '/elections/$id/ballots/$ballotId/preview': typeof ProtectedElectionsIdBallotsBallotIdPreviewRoute
  '/elections/$id/contests/$contestId/candidates/new': typeof ProtectedElectionsIdContestsContestIdCandidatesNewRoute
  '/elections/$id/contests/$contestId/candidates/review': typeof ProtectedElectionsIdContestsContestIdCandidatesReviewRoute
  '/elections/$id/contests/$contestId/candidates': typeof ProtectedElectionsIdContestsContestIdCandidatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/admin': typeof ProtectedAdminRoute
  '/_protected/audit': typeof ProtectedAuditRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/silent-renew': typeof AuthSilentRenewRoute
  '/voters/register': typeof VotersRegisterRoute
  '/_protected/elections/$id': typeof ProtectedElectionsIdRouteWithChildren
  '/_protected/elections/new': typeof ProtectedElectionsNewRoute
  '/_protected/vote/session': typeof ProtectedVoteSessionRoute
  '/_protected/voters/eligibility': typeof ProtectedVotersEligibilityRoute
  '/_protected/elections/': typeof ProtectedElectionsIndexRoute
  '/_protected/voters/': typeof ProtectedVotersIndexRoute
  '/_protected/elections/$id/ballots': typeof ProtectedElectionsIdBallotsRouteWithChildren
  '/_protected/elections/$id/contests': typeof ProtectedElectionsIdContestsRouteWithChildren
  '/_protected/elections/$id/results': typeof ProtectedElectionsIdResultsRouteWithChildren
  '/_protected/elections/$id/results/tabulation': typeof ProtectedElectionsIdResultsTabulationRoute
  '/_protected/elections/$id/ballots/$ballotId/preview': typeof ProtectedElectionsIdBallotsBallotIdPreviewRoute
  '/_protected/elections/$id/contests/$contestId/candidates/new': typeof ProtectedElectionsIdContestsContestIdCandidatesNewRoute
  '/_protected/elections/$id/contests/$contestId/candidates/review': typeof ProtectedElectionsIdContestsContestIdCandidatesReviewRoute
  '/_protected/elections/$id/contests/$contestId/candidates/': typeof ProtectedElectionsIdContestsContestIdCandidatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/audit'
    | '/auth/callback'
    | '/auth/silent-renew'
    | '/voters/register'
    | '/elections/$id'
    | '/elections/new'
    | '/vote/session'
    | '/voters/eligibility'
    | '/elections/'
    | '/voters/'
    | '/elections/$id/ballots'
    | '/elections/$id/contests'
    | '/elections/$id/results'
    | '/elections/$id/results/tabulation'
    | '/elections/$id/ballots/$ballotId/preview'
    | '/elections/$id/contests/$contestId/candidates/new'
    | '/elections/$id/contests/$contestId/candidates/review'
    | '/elections/$id/contests/$contestId/candidates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/audit'
    | '/auth/callback'
    | '/auth/silent-renew'
    | '/voters/register'
    | '/elections/$id'
    | '/elections/new'
    | '/vote/session'
    | '/voters/eligibility'
    | '/elections'
    | '/voters'
    | '/elections/$id/ballots'
    | '/elections/$id/contests'
    | '/elections/$id/results'
    | '/elections/$id/results/tabulation'
    | '/elections/$id/ballots/$ballotId/preview'
    | '/elections/$id/contests/$contestId/candidates/new'
    | '/elections/$id/contests/$contestId/candidates/review'
    | '/elections/$id/contests/$contestId/candidates'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/_protected/admin'
    | '/_protected/audit'
    | '/auth/callback'
    | '/auth/silent-renew'
    | '/voters/register'
    | '/_protected/elections/$id'
    | '/_protected/elections/new'
    | '/_protected/vote/session'
    | '/_protected/voters/eligibility'
    | '/_protected/elections/'
    | '/_protected/voters/'
    | '/_protected/elections/$id/ballots'
    | '/_protected/elections/$id/contests'
    | '/_protected/elections/$id/results'
    | '/_protected/elections/$id/results/tabulation'
    | '/_protected/elections/$id/ballots/$ballotId/preview'
    | '/_protected/elections/$id/contests/$contestId/candidates/new'
    | '/_protected/elections/$id/contests/$contestId/candidates/review'
    | '/_protected/elections/$id/contests/$contestId/candidates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthSilentRenewRoute: typeof AuthSilentRenewRoute
  VotersRegisterRoute: typeof VotersRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voters/register': {
      id: '/voters/register'
      path: '/voters/register'
      fullPath: '/voters/register'
      preLoaderRoute: typeof VotersRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/silent-renew': {
      id: '/auth/silent-renew'
      path: '/auth/silent-renew'
      fullPath: '/auth/silent-renew'
      preLoaderRoute: typeof AuthSilentRenewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/audit': {
      id: '/_protected/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof ProtectedAuditRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/voters/': {
      id: '/_protected/voters/'
      path: '/voters'
      fullPath: '/voters/'
      preLoaderRoute: typeof ProtectedVotersIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/elections/': {
      id: '/_protected/elections/'
      path: '/elections'
      fullPath: '/elections/'
      preLoaderRoute: typeof ProtectedElectionsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/voters/eligibility': {
      id: '/_protected/voters/eligibility'
      path: '/voters/eligibility'
      fullPath: '/voters/eligibility'
      preLoaderRoute: typeof ProtectedVotersEligibilityRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/vote/session': {
      id: '/_protected/vote/session'
      path: '/vote/session'
      fullPath: '/vote/session'
      preLoaderRoute: typeof ProtectedVoteSessionRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/elections/new': {
      id: '/_protected/elections/new'
      path: '/elections/new'
      fullPath: '/elections/new'
      preLoaderRoute: typeof ProtectedElectionsNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/elections/$id': {
      id: '/_protected/elections/$id'
      path: '/elections/$id'
      fullPath: '/elections/$id'
      preLoaderRoute: typeof ProtectedElectionsIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/elections/$id/results': {
      id: '/_protected/elections/$id/results'
      path: '/results'
      fullPath: '/elections/$id/results'
      preLoaderRoute: typeof ProtectedElectionsIdResultsRouteImport
      parentRoute: typeof ProtectedElectionsIdRoute
    }
    '/_protected/elections/$id/contests': {
      id: '/_protected/elections/$id/contests'
      path: '/contests'
      fullPath: '/elections/$id/contests'
      preLoaderRoute: typeof ProtectedElectionsIdContestsRouteImport
      parentRoute: typeof ProtectedElectionsIdRoute
    }
    '/_protected/elections/$id/ballots': {
      id: '/_protected/elections/$id/ballots'
      path: '/ballots'
      fullPath: '/elections/$id/ballots'
      preLoaderRoute: typeof ProtectedElectionsIdBallotsRouteImport
      parentRoute: typeof ProtectedElectionsIdRoute
    }
    '/_protected/elections/$id/results/tabulation': {
      id: '/_protected/elections/$id/results/tabulation'
      path: '/tabulation'
      fullPath: '/elections/$id/results/tabulation'
      preLoaderRoute: typeof ProtectedElectionsIdResultsTabulationRouteImport
      parentRoute: typeof ProtectedElectionsIdResultsRoute
    }
    '/_protected/elections/$id/ballots/$ballotId/preview': {
      id: '/_protected/elections/$id/ballots/$ballotId/preview'
      path: '/$ballotId/preview'
      fullPath: '/elections/$id/ballots/$ballotId/preview'
      preLoaderRoute: typeof ProtectedElectionsIdBallotsBallotIdPreviewRouteImport
      parentRoute: typeof ProtectedElectionsIdBallotsRoute
    }
    '/_protected/elections/$id/contests/$contestId/candidates/': {
      id: '/_protected/elections/$id/contests/$contestId/candidates/'
      path: '/$contestId/candidates'
      fullPath: '/elections/$id/contests/$contestId/candidates/'
      preLoaderRoute: typeof ProtectedElectionsIdContestsContestIdCandidatesIndexRouteImport
      parentRoute: typeof ProtectedElectionsIdContestsRoute
    }
    '/_protected/elections/$id/contests/$contestId/candidates/review': {
      id: '/_protected/elections/$id/contests/$contestId/candidates/review'
      path: '/$contestId/candidates/review'
      fullPath: '/elections/$id/contests/$contestId/candidates/review'
      preLoaderRoute: typeof ProtectedElectionsIdContestsContestIdCandidatesReviewRouteImport
      parentRoute: typeof ProtectedElectionsIdContestsRoute
    }
    '/_protected/elections/$id/contests/$contestId/candidates/new': {
      id: '/_protected/elections/$id/contests/$contestId/candidates/new'
      path: '/$contestId/candidates/new'
      fullPath: '/elections/$id/contests/$contestId/candidates/new'
      preLoaderRoute: typeof ProtectedElectionsIdContestsContestIdCandidatesNewRouteImport
      parentRoute: typeof ProtectedElectionsIdContestsRoute
    }
  }
}

interface ProtectedElectionsIdBallotsRouteChildren {
  ProtectedElectionsIdBallotsBallotIdPreviewRoute: typeof ProtectedElectionsIdBallotsBallotIdPreviewRoute
}

const ProtectedElectionsIdBallotsRouteChildren: ProtectedElectionsIdBallotsRouteChildren =
  {
    ProtectedElectionsIdBallotsBallotIdPreviewRoute:
      ProtectedElectionsIdBallotsBallotIdPreviewRoute,
  }

const ProtectedElectionsIdBallotsRouteWithChildren =
  ProtectedElectionsIdBallotsRoute._addFileChildren(
    ProtectedElectionsIdBallotsRouteChildren,
  )

interface ProtectedElectionsIdContestsRouteChildren {
  ProtectedElectionsIdContestsContestIdCandidatesNewRoute: typeof ProtectedElectionsIdContestsContestIdCandidatesNewRoute
  ProtectedElectionsIdContestsContestIdCandidatesReviewRoute: typeof ProtectedElectionsIdContestsContestIdCandidatesReviewRoute
  ProtectedElectionsIdContestsContestIdCandidatesIndexRoute: typeof ProtectedElectionsIdContestsContestIdCandidatesIndexRoute
}

const ProtectedElectionsIdContestsRouteChildren: ProtectedElectionsIdContestsRouteChildren =
  {
    ProtectedElectionsIdContestsContestIdCandidatesNewRoute:
      ProtectedElectionsIdContestsContestIdCandidatesNewRoute,
    ProtectedElectionsIdContestsContestIdCandidatesReviewRoute:
      ProtectedElectionsIdContestsContestIdCandidatesReviewRoute,
    ProtectedElectionsIdContestsContestIdCandidatesIndexRoute:
      ProtectedElectionsIdContestsContestIdCandidatesIndexRoute,
  }

const ProtectedElectionsIdContestsRouteWithChildren =
  ProtectedElectionsIdContestsRoute._addFileChildren(
    ProtectedElectionsIdContestsRouteChildren,
  )

interface ProtectedElectionsIdResultsRouteChildren {
  ProtectedElectionsIdResultsTabulationRoute: typeof ProtectedElectionsIdResultsTabulationRoute
}

const ProtectedElectionsIdResultsRouteChildren: ProtectedElectionsIdResultsRouteChildren =
  {
    ProtectedElectionsIdResultsTabulationRoute:
      ProtectedElectionsIdResultsTabulationRoute,
  }

const ProtectedElectionsIdResultsRouteWithChildren =
  ProtectedElectionsIdResultsRoute._addFileChildren(
    ProtectedElectionsIdResultsRouteChildren,
  )

interface ProtectedElectionsIdRouteChildren {
  ProtectedElectionsIdBallotsRoute: typeof ProtectedElectionsIdBallotsRouteWithChildren
  ProtectedElectionsIdContestsRoute: typeof ProtectedElectionsIdContestsRouteWithChildren
  ProtectedElectionsIdResultsRoute: typeof ProtectedElectionsIdResultsRouteWithChildren
}

const ProtectedElectionsIdRouteChildren: ProtectedElectionsIdRouteChildren = {
  ProtectedElectionsIdBallotsRoute:
    ProtectedElectionsIdBallotsRouteWithChildren,
  ProtectedElectionsIdContestsRoute:
    ProtectedElectionsIdContestsRouteWithChildren,
  ProtectedElectionsIdResultsRoute:
    ProtectedElectionsIdResultsRouteWithChildren,
}

const ProtectedElectionsIdRouteWithChildren =
  ProtectedElectionsIdRoute._addFileChildren(ProtectedElectionsIdRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRoute
  ProtectedAuditRoute: typeof ProtectedAuditRoute
  ProtectedElectionsIdRoute: typeof ProtectedElectionsIdRouteWithChildren
  ProtectedElectionsNewRoute: typeof ProtectedElectionsNewRoute
  ProtectedVoteSessionRoute: typeof ProtectedVoteSessionRoute
  ProtectedVotersEligibilityRoute: typeof ProtectedVotersEligibilityRoute
  ProtectedElectionsIndexRoute: typeof ProtectedElectionsIndexRoute
  ProtectedVotersIndexRoute: typeof ProtectedVotersIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRoute,
  ProtectedAuditRoute: ProtectedAuditRoute,
  ProtectedElectionsIdRoute: ProtectedElectionsIdRouteWithChildren,
  ProtectedElectionsNewRoute: ProtectedElectionsNewRoute,
  ProtectedVoteSessionRoute: ProtectedVoteSessionRoute,
  ProtectedVotersEligibilityRoute: ProtectedVotersEligibilityRoute,
  ProtectedElectionsIndexRoute: ProtectedElectionsIndexRoute,
  ProtectedVotersIndexRoute: ProtectedVotersIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthSilentRenewRoute: AuthSilentRenewRoute,
  VotersRegisterRoute: VotersRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
