apiVersion: v1
kind: Service
metadata:
  name: {{ include "mirems-platform.fullname" . }}-core-api
  labels:
    {{- include "mirems-platform.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: core-api
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      targetPort: http
