apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mirems-platform.fullname" . }}-core-api
  labels:
    {{- include "mirems-platform.labels" . | nindent 4 }}
automountServiceAccountToken: false
