package io.mirems.core.bpmn.audit;

import io.mirems.core.domain.audit.AuditEvent;
import java.nio.charset.StandardCharsets;
import java.time.OffsetDateTime;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.springframework.stereotype.Component;

@Component
public class SimpleAuditReportGenerator implements AuditReportGenerator {
    @Override
    public AuditReport generate(AuditReviewRequest request, List<AuditEvent> auditEvents) {
        Objects.requireNonNull(request, "request is required");
        List<AuditEvent> sortedEvents = auditEvents.stream()
                .sorted(Comparator.comparing(AuditEvent::getOccurredAt).thenComparing(AuditEvent::getId))
                .toList();
        String json = toJson(request, sortedEvents);
        String pdfBody = "MiREMS Post-Election Audit Report\n"
                + "Report ID: " + request.reportId() + "\n"
                + "Election ID: " + request.electionId() + "\n"
                + "Generated By: " + request.initiatedBy() + "\n"
                + "Generated At: " + request.generatedAt() + "\n"
                + "Audit Event Count: " + sortedEvents.size() + "\n"
                + sortedEvents.stream()
                        .map(event -> event.getOccurredAt() + " " + event.getEventType() + " by " + event.getActorId())
                        .reduce("", (left, right) -> left + right + "\n");
        return new AuditReport(
                request.reportId(),
                request.electionId(),
                request.initiatedBy(),
                request.generatedAt(),
                sortedEvents.size(),
                "audit-report-" + request.electionId() + ".json",
                "application/json",
                json.getBytes(StandardCharsets.UTF_8),
                "audit-report-" + request.electionId() + ".pdf",
                "application/pdf",
                minimalPdf(pdfBody));
    }

    private String toJson(AuditReviewRequest request, List<AuditEvent> events) {
        StringBuilder builder = new StringBuilder();
        builder.append('{')
                .append("\"reportId\":\"").append(request.reportId()).append("\",")
                .append("\"electionId\":\"").append(request.electionId()).append("\",")
                .append("\"generatedBy\":\"").append(escape(request.initiatedBy())).append("\",")
                .append("\"generatedAt\":\"").append(request.generatedAt()).append("\",")
                .append("\"eventCount\":").append(events.size()).append(',')
                .append("\"events\":[");
        for (int index = 0; index < events.size(); index++) {
            if (index > 0) {
                builder.append(',');
            }
            AuditEvent event = events.get(index);
            builder.append('{')
                    .append("\"id\":\"").append(event.getId()).append("\",")
                    .append("\"eventType\":\"").append(escape(event.getEventType())).append("\",")
                    .append("\"aggregateId\":\"").append(event.getAggregateId()).append("\",")
                    .append("\"aggregateType\":\"").append(escape(event.getAggregateType())).append("\",")
                    .append("\"actorId\":\"").append(escape(event.getActorId())).append("\",")
                    .append("\"occurredAt\":\"").append(event.getOccurredAt()).append("\",")
                    .append("\"payload\":").append(mapToJson(event.getPayload()))
                    .append('}');
        }
        return builder.append("]}").toString();
    }

    private String mapToJson(Map<String, Object> payload) {
        StringBuilder builder = new StringBuilder("{");
        int index = 0;
        for (Map.Entry<String, Object> entry : payload.entrySet().stream()
                .sorted(Map.Entry.comparingByKey())
                .toList()) {
            if (index++ > 0) {
                builder.append(',');
            }
            builder.append("\"").append(escape(entry.getKey())).append("\":");
            Object value = entry.getValue();
            if (value instanceof Number || value instanceof Boolean) {
                builder.append(value);
            } else {
                builder.append("\"").append(escape(String.valueOf(value))).append("\"");
            }
        }
        return builder.append('}').toString();
    }

    private byte[] minimalPdf(String body) {
        String escaped = body.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)").replace("\n", "\\n");
        String pdf = "%PDF-1.4\n"
                + "1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj\n"
                + "2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj\n"
                + "3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R >> endobj\n"
                + "4 0 obj << /Length " + (escaped.length() + 47) + " >> stream\n"
                + "BT /F1 10 Tf 50 740 Td (" + escaped + ") Tj ET\n"
                + "endstream endobj\n"
                + "xref\n0 5\n0000000000 65535 f \n"
                + "trailer << /Root 1 0 R /Size 5 >>\nstartxref\n0\n%%EOF\n";
        return pdf.getBytes(StandardCharsets.UTF_8);
    }

    private static String escape(String value) {
        return value.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
